### PR TITLE
fix(Const): Removed use of const in strict mode

### PR DESCRIPTION
**Pull request by wski**

### CODE REVIEW

**Comment by wski** [comment]
@clarkjefcoat @hoganmaps

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by rpokorny** [comment]
Just wondering why this was done - `const` is part of ES6 so I would think we would be adding it, not removing it

**Comment by wski** [comment]
For some reason the bundle had const instead of being shimmed to bar or whatever Babel turns it into for older browsers, it stayed in the release. So browsers without ES6 support were complaining.

**Comment by rpokorny** [comment]
Odd, in my current project Babel converts `const` to `var` and handles the scoping differences.

**Comment by clarkjefcoat** [comment]
Before this change in Chrome 36 the console said "Uncaught SyntaxError: Use of const in strict mode".

**Comment by wski** [comment]
It's worth noting I don't think we use let or const in any of our other projects (although we have support to do so). Perhaps there is a setting that needs to be enabled (or disabled) when building. 




We can investigate further in the future, though I don't see any reason to sink a lot of time into it at the moment.

**Comment by hoganmaps** [comment]
good enough :+1:

**Pull request merged**
