### PR TITLE
First draft at splitting the help resources into smaller chunks. Link…

### PR DESCRIPTION
**Pull request by stephaniesaylor**
…s are broken.

### CODE REVIEW

**Comment by wski** [comment]
There are a few things that need fixing, is there a way to disable your editor from adding special things like `pbzloc="0"` if not we SHOULD be okay but it would be better to remove them. Also we need to add a few things to .gitiginore. I can add the gitignore things if you'd like

**Comment by stephaniesaylor** [comment]
You need to pull. I cleaned that up weeks ago and have been writing in Notepad++
Also, that mocks/ContentSteward.html page was depricated after what Sarah and Bethany decided at our last meeting. I'll give you access to a list of pages and the titles that you should use in the help UI. 
Last thing, I've never added .gitiginore. I can add it if someone shows me how. Thanks!

**Comment by wski** [comment]
It's in the commit diff log, I have not pulled it yet. If we don't need those anymore we should delete them and re-run the python script I added. I'll Slack you about the .gitignore its pretty easy :)

Please see here: https://github.com/ozone-development/ozp-help/pull/10/files to make sure all the files you're wanting to commit with this PR is accurate.

**Comment by stephaniesaylor** [comment]
Thanks Matt!

**Pull request merged**
